from django.core.management.base import BaseCommand
from django.db import transaction
from decimal import Decimal
from insumo.models import Insumo, GrupoInsumo


class Command(BaseCommand):
    help = 'Carga insumos iniciales para el taller Iam Car'

    @transaction.atomic
    def handle(self, *args, **options):
        insumos = [
            # ===================== LUBRICANTES Y FLUIDOS =====================
            # --- Motor naftero (gasolina) ---
            {
                "nombre": "Aceite Motor 0W20 Sintético (Nafta)",
                "descripcion": "Aceite sintético 0W20 para motores a gasolina modernos con alta eficiencia.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("98000.00"),
                "stock_actual": Decimal("20.00"),
                "stock_minimo": Decimal("5.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Aceite Motor 5W30 Sintético (Nafta)",
                "descripcion": "Aceite sintético 5W30 para motores a gasolina; arranque en frío y protección a altas temperaturas.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("92000.00"),
                "stock_actual": Decimal("24.00"),
                "stock_minimo": Decimal("6.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Aceite Motor 10W40 Semi-Sintético (Nafta)",
                "descripcion": "Aceite semi-sintético 10W40 para gasolina; equilibrio entre protección y costo.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("78000.00"),
                "stock_actual": Decimal("18.00"),
                "stock_minimo": Decimal("5.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Aceite Motor 20W50 Mineral (Nafta)",
                "descripcion": "Aceite mineral 20W50 para vehículos a gasolina de mayor kilometraje o climas cálidos.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("62000.00"),
                "stock_actual": Decimal("16.00"),
                "stock_minimo": Decimal("4.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            # --- Motor diésel liviano (pickup/SUV/LDV) ---
            {
                "nombre": "Aceite Motor 5W40 Sintético (Diésel liviano)",
                "descripcion": "Aceite sintético 5W40 para diésel liviano; adecuado para turbodiésel modernos.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("99000.00"),
                "stock_actual": Decimal("14.00"),
                "stock_minimo": Decimal("4.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Aceite Motor 15W40 Mineral CI-4 (Diésel liviano)",
                "descripcion": "Aceite 15W40 con especificación CI-4 para diésel liviano; alta detergencia y protección.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("70000.00"),
                "stock_actual": Decimal("22.00"),
                "stock_minimo": Decimal("6.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            # --- Motor diésel pesado (HD/maquinaria) ---
            {
                "nombre": "Aceite Motor 15W40 CI-4/SL (Diésel pesado)",
                "descripcion": "Lubricante 15W40 para diésel pesado y flotas; estabilidad a alta carga y hollín.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("74000.00"),
                "stock_actual": Decimal("25.00"),
                "stock_minimo": Decimal("8.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Aceite Motor 10W30 FA-4 (Diésel pesado moderno)",
                "descripcion": "Aceite de baja viscosidad FA-4 para diésel pesado modernos orientado a ahorro de combustible.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("105000.00"),
                "stock_actual": Decimal("10.00"),
                "stock_minimo": Decimal("3.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            # --- Motocicleta ---
            {
                "nombre": "Aceite Moto 10W40 4T Sintético (JASO MA2)",
                "descripcion": "Aceite para motos 4T con embrague húmedo; certificación JASO MA2.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("68000.00"),
                "stock_actual": Decimal("20.00"),
                "stock_minimo": Decimal("5.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Aceite Moto 2T",
                "descripcion": "Aceite 2 tiempos para mezcla; baja formación de humo.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("52000.00"),
                "stock_actual": Decimal("14.00"),
                "stock_minimo": Decimal("4.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            # --- Transmisión / Diferencial / Dirección ---
            {
                "nombre": "ATF Dexron III",
                "descripcion": "Fluido para cajas automáticas y dirección asistida que requieran Dexron III.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("56000.00"),
                "stock_actual": Decimal("18.00"),
                "stock_minimo": Decimal("5.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Fluido CVT",
                "descripcion": "Fluido específico para transmisiones continuamente variables (CVT).",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("98000.00"),
                "stock_actual": Decimal("8.00"),
                "stock_minimo": Decimal("2.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Aceite Engranajes 75W-90 (GL-5)",
                "descripcion": "Aceite para cajas manuales y diferenciales; especificación GL-5 75W-90.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("78000.00"),
                "stock_actual": Decimal("12.00"),
                "stock_minimo": Decimal("3.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Aceite Diferencial 85W-140",
                "descripcion": "Lubricante para diferenciales de servicio severo 85W-140.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("80000.00"),
                "stock_actual": Decimal("10.00"),
                "stock_minimo": Decimal("3.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            # --- Hidráulico / Grasas ---
            {
                "nombre": "Aceite Hidráulico ISO 46",
                "descripcion": "Fluido hidráulico ISO VG 46 para prensa y equipos.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("45000.00"),
                "stock_actual": Decimal("20.00"),
                "stock_minimo": Decimal("5.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Grasa Multipropósito NLGI 2",
                "descripcion": "Grasa a base de litio para rodamientos, chasis y usos generales.",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.KG,
                "costo_unitario": Decimal("35000.00"),
                "stock_actual": Decimal("15.00"),
                "stock_minimo": Decimal("4.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Aceite Motor 10W40 Sintético",
                "descripcion": "Aceite sintético para motor, grado 10W40",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("85000.00"),
                "stock_actual": Decimal("24.00"),
                "stock_minimo": Decimal("6.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Aceite Motor 5W30 Semi-Sintético",
                "descripcion": "Aceite semi-sintético 5W30 para vehículos livianos",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Lubricantes",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("68000.00"),
                "stock_actual": Decimal("18.00"),
                "stock_minimo": Decimal("5.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Líquido de frenos DOT 4",
                "descripcion": "Fluido de frenos DOT4",
                "grupo": GrupoInsumo.INSUMO,
                "categoria": "Fluidos",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("42000.00"),
                "stock_actual": Decimal("12.00"),
                "stock_minimo": Decimal("4.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },

            # ===================== FILTROS (REPUESTOS CON GARANTÍA) =====================
            {
                "nombre": "Filtro de aceite spin-on (M20x1.5)",
                "descripcion": "Filtro de aceite rosca M20x1.5, media de celulosa.",
                "grupo": GrupoInsumo.REPUESTO,
                "categoria": "Filtros",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("35000.00"),
                "stock_actual": Decimal("24.00"),
                "stock_minimo": Decimal("6.00"),
                "tiene_garantia": True,
                "garantia_meses": 6,
                "is_active": True,
            },
            {
                "nombre": "Filtro de aceite spin-on (3/4\"-16)",
                "descripcion": "Filtro de aceite rosca 3/4\"-16, compatible con múltiples marcas.",
                "grupo": GrupoInsumo.REPUESTO,
                "categoria": "Filtros",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("36000.00"),
                "stock_actual": Decimal("20.00"),
                "stock_minimo": Decimal("6.00"),
                "tiene_garantia": True,
                "garantia_meses": 6,
                "is_active": True,
            },
            {
                "nombre": "Filtro de aceite cartucho 1.6L",
                "descripcion": "Cartucho de aceite para motores 1.6L, elemento sintético.",
                "grupo": GrupoInsumo.REPUESTO,
                "categoria": "Filtros",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("42000.00"),
                "stock_actual": Decimal("18.00"),
                "stock_minimo": Decimal("5.00"),
                "tiene_garantia": True,
                "garantia_meses": 6,
                "is_active": True,
            },
            {
                "nombre": "Filtro de aceite cartucho 2.0L",
                "descripcion": "Cartucho de aceite para motores 2.0L, alta capacidad.",
                "grupo": GrupoInsumo.REPUESTO,
                "categoria": "Filtros",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("48000.00"),
                "stock_actual": Decimal("16.00"),
                "stock_minimo": Decimal("4.00"),
                "tiene_garantia": True,
                "garantia_meses": 6,
                "is_active": True,
            },
            {
                "nombre": "Filtro de aire panel (chico)",
                "descripcion": "Filtro de aire tipo panel, medidas compactas para hatchback.",
                "grupo": GrupoInsumo.REPUESTO,
                "categoria": "Filtros",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("30000.00"),
                "stock_actual": Decimal("22.00"),
                "stock_minimo": Decimal("6.00"),
                "tiene_garantia": True,
                "garantia_meses": 3,
                "is_active": True,
            },
            {
                "nombre": "Filtro de aire panel (mediano)",
                "descripcion": "Filtro de aire tipo panel, medidas estándar sedán/SUV liviano.",
                "grupo": GrupoInsumo.REPUESTO,
                "categoria": "Filtros",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("36000.00"),
                "stock_actual": Decimal("20.00"),
                "stock_minimo": Decimal("6.00"),
                "tiene_garantia": True,
                "garantia_meses": 3,
                "is_active": True,
            },
            {
                "nombre": "Filtro de aire panel (grande)",
                "descripcion": "Filtro de aire panel grande para SUV/pickup.",
                "grupo": GrupoInsumo.REPUESTO,
                "categoria": "Filtros",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("42000.00"),
                "stock_actual": Decimal("16.00"),
                "stock_minimo": Decimal("4.00"),
                "tiene_garantia": True,
                "garantia_meses": 3,
                "is_active": True,
            },
            {
                "nombre": "Filtro de combustible",
                "descripcion": "Filtro de combustible universal para sistemas de inyección electrónica.",
                "grupo": GrupoInsumo.REPUESTO,
                "categoria": "Filtros",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("42000.00"),
                "stock_actual": Decimal("16.00"),
                "stock_minimo": Decimal("4.00"),
                "tiene_garantia": True,
                "garantia_meses": 3,
                "is_active": True,
            },
            {
                "nombre": "Filtro de cabina (antipolen)",
                "descripcion": "Filtro de aire de cabina estándar con protección antipolen.",
                "grupo": GrupoInsumo.REPUESTO,
                "categoria": "Filtros",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("35000.00"),
                "stock_actual": Decimal("20.00"),
                "stock_minimo": Decimal("5.00"),
                "tiene_garantia": True,
                "garantia_meses": 3,
                "is_active": True,
            },

            # ===================== SISTEMA DE FRENOS (REPUESTOS CON GARANTÍA) =====================
            {
                "nombre": "Pastillas de freno NAO (orgánicas) - juego delantero",
                "descripcion": "Compuesto NAO: silenciosas y suaves, uso urbano/diario.",
                "grupo": GrupoInsumo.REPUESTO,
                "categoria": "Frenos",
                "unidad": Insumo.Unidad.PA,
                "costo_unitario": Decimal("120000.00"),
                "stock_actual": Decimal("12.00"),
                "stock_minimo": Decimal("3.00"),
                "tiene_garantia": True,
                "garantia_meses": 12,
                "is_active": True,
            },
            {
                "nombre": "Pastillas de freno Semimetálicas - juego delantero",
                "descripcion": "Alto desempeño térmico, ideal para SUV/pickup.",
                "grupo": GrupoInsumo.REPUESTO,
                "categoria": "Frenos",
                "unidad": Insumo.Unidad.PA,
                "costo_unitario": Decimal("180000.00"),
                "stock_actual": Decimal("8.00"),
                "stock_minimo": Decimal("2.00"),
                "tiene_garantia": True,
                "garantia_meses": 12,
                "is_active": True,
            },
            {
                "nombre": "Pastillas de freno Cerámicas Premium - juego delantero",
                "descripcion": "Bajo polvo y ruido, estable en amplio rango térmico.",
                "grupo": GrupoInsumo.REPUESTO,
                "categoria": "Frenos",
                "unidad": Insumo.Unidad.PA,
                "costo_unitario": Decimal("240000.00"),
                "stock_actual": Decimal("6.00"),
                "stock_minimo": Decimal("2.00"),
                "tiene_garantia": True,
                "garantia_meses": 12,
                "is_active": True,
            },
            {
                "nombre": "Discos de freno ventilados (par)",
                "descripcion": "Par de discos de freno delanteros ventilados para mejor refrigeración.",
                "grupo": GrupoInsumo.REPUESTO,
                "categoria": "Frenos",
                "unidad": Insumo.Unidad.PA,
                "costo_unitario": Decimal("320000.00"),
                "stock_actual": Decimal("6.00"),
                "stock_minimo": Decimal("2.00"),
                "tiene_garantia": True,
                "garantia_meses": 12,
                "is_active": True,
            },

            # ===================== HERRAMIENTAS =====================
            {
                "nombre": "Juego de llaves combinadas (6–22 mm)",
                "descripcion": "Set de llaves combinadas (abierta + estrella) en milímetros.",
                "grupo": GrupoInsumo.HERRAMIENTA,
                "categoria": "Herramientas manuales",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("180000.00"),
                "stock_actual": Decimal("6.00"),
                "stock_minimo": Decimal("2.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Carraca 1/2\" + juego de vasos (10–24 mm)",
                "descripcion": "Trinquete 1/2 pulgada con vasos métricos y extensión.",
                "grupo": GrupoInsumo.HERRAMIENTA,
                "categoria": "Herramientas manuales",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("280000.00"),
                "stock_actual": Decimal("5.00"),
                "stock_minimo": Decimal("1.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Torquímetro 1/2\" 20-200 Nm",
                "descripcion": "Llave de torque para ajuste preciso de tornillos.",
                "grupo": GrupoInsumo.HERRAMIENTA,
                "categoria": "Herramientas de medición",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("450000.00"),
                "stock_actual": Decimal("3.00"),
                "stock_minimo": Decimal("1.00"),
                "tiene_garantia": True,
                "garantia_meses": 12,
                "is_active": True,
            },
            {
                "nombre": "Multímetro automotriz",
                "descripcion": "Multímetro digital para diagnóstico eléctrico automotriz.",
                "grupo": GrupoInsumo.HERRAMIENTA,
                "categoria": "Herramientas de medición",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("180000.00"),
                "stock_actual": Decimal("4.00"),
                "stock_minimo": Decimal("1.00"),
                "tiene_garantia": True,
                "garantia_meses": 12,
                "is_active": True,
            },

            # ===================== MATERIALES DE LIMPIEZA Y MANTENIMIENTO =====================
            {
                "nombre": "Limpiador de cuerpo de aceleración",
                "descripcion": "Spray limpiador especial para cuerpo de aceleración y válvulas.",
                "grupo": GrupoInsumo.LIMPIEZA_MANTENIMIENTO,
                "categoria": "Limpieza",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("22000.00"),
                "stock_actual": Decimal("15.00"),
                "stock_minimo": Decimal("4.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Desengrasante automotriz",
                "descripcion": "Desengrasante en spray para motor y piezas mecánicas.",
                "grupo": GrupoInsumo.LIMPIEZA_MANTENIMIENTO,
                "categoria": "Limpieza",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("18000.00"),
                "stock_actual": Decimal("20.00"),
                "stock_minimo": Decimal("5.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },
            {
                "nombre": "Cera automotriz líquida",
                "descripcion": "Cera para protección y brillo final de la pintura.",
                "grupo": GrupoInsumo.LIMPIEZA_MANTENIMIENTO,
                "categoria": "Limpieza",
                "unidad": Insumo.Unidad.LT,
                "costo_unitario": Decimal("32000.00"),
                "stock_actual": Decimal("10.00"),
                "stock_minimo": Decimal("3.00"),
                "tiene_garantia": False,
                "garantia_meses": None,
                "is_active": True,
            },

            # ===================== INSUMOS PARA VENTA =====================
            {
                "nombre": "Lámpara H4 halógena",
                "descripcion": "Lámpara halógena H4 para faros delanteros.",
                "grupo": GrupoInsumo.INSUMO_VENTA,
                "categoria": "Iluminación",
                "unidad": Insumo.Unidad.PA,
                "costo_unitario": Decimal("25000.00"),
                "stock_actual": Decimal("20.00"),
                "stock_minimo": Decimal("5.00"),
                "tiene_garantia": True,
                "garantia_meses": 3,
                "is_active": True,
            },
            {
                "nombre": "Lámpara LED H7 6000K",
                "descripcion": "Lámpara LED para faros delanteros, alta luminosidad.",
                "grupo": GrupoInsumo.INSUMO_VENTA,
                "categoria": "Iluminación",
                "unidad": Insumo.Unidad.PA,
                "costo_unitario": Decimal("85000.00"),
                "stock_actual": Decimal("8.00"),
                "stock_minimo": Decimal("2.00"),
                "tiene_garantia": True,
                "garantia_meses": 12,
                "is_active": True,
            },
            {
                "nombre": "Batería libre de mantenimiento 12V 60Ah",
                "descripcion": "Batería automotriz 12V 60Ah libre de mantenimiento.",
                "grupo": GrupoInsumo.INSUMO_VENTA,
                "categoria": "Eléctrico",
                "unidad": Insumo.Unidad.UN,
                "costo_unitario": Decimal("320000.00"),
                "stock_actual": Decimal("6.00"),
                "stock_minimo": Decimal("2.00"),
                "tiene_garantia": True,
                "garantia_meses": 12,
                "is_active": True,
            },
        ]

        created_count = 0
        updated_count = 0
        skipped_count = 0

        for insumo_data in insumos:
            nombre = insumo_data['nombre']
            try:
                insumo = Insumo.objects.get(nombre=nombre)
                # Actualizar insumo existente
                for key, value in insumo_data.items():
                    if key != 'nombre':  # No actualizar el nombre
                        setattr(insumo, key, value)
                insumo.save()
                updated_count += 1
                self.stdout.write(self.style.WARNING(f'⮐ {nombre} (actualizado)'))
            except Insumo.DoesNotExist:
                # Crear nuevo insumo
                Insumo.objects.create(**insumo_data)
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'✓ {nombre}'))
            except Exception as e:
                skipped_count += 1
                self.stdout.write(self.style.ERROR(f'✗ Error con {nombre}: {str(e)}'))

        self.stdout.write(self.style.SUCCESS(
            f'\n{"="*50}\n'
            f'PROCESO COMPLETADO:\n'
            f'✓ {created_count} insumos creados\n'
            f'⮐ {updated_count} insumos actualizados\n'
            f'✗ {skipped_count} insumos con error\n'
            f'{"="*50}'
        ))