# Generated by Django 5.2.5 on 2025-09-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logenvio',
            name='cliente_id',
        ),
        migrations.AddField(
            model_name='logenvio',
            name='referencia_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logenvio',
            name='tipo',
            field=models.CharField(choices=[('bienvenida', 'Bienvenida'), ('orden_lista', 'Orden lista'), ('bajo_insumo', 'Bajo insumo'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
    ]
