# Generated by Django 5.2.3 on 2025-09-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150, unique=True, verbose_name='Razón social')),
                ('ruc', models.CharField(max_length=25, unique=True, verbose_name='RUC')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['razon_social'],
                'permissions': [('gestionar_proveedores', 'Puede gestionar proveedores'), ('ver_proveedores', 'Puede ver proveedores'), ('agregar_proveedores', 'Puede registrar proveedores'), ('editar_proveedores', 'Puede actualizar proveedores'), ('desactivar_proveedores', 'Puede desactivar/activar proveedores')],
            },
        ),
    ]
