# Generated by Django 5.2.5 on 2025-09-30 05:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ('-fecha_registro',), 'permissions': [('gestionar_proveedores', 'Puede gestionar proveedores'), ('ver_proveedores', 'Puede ver proveedores'), ('agregar_proveedores', 'Puede registrar proveedores'), ('editar_proveedores', 'Puede actualizar proveedores'), ('desactivar_proveedores', 'Puede desactivar/activar proveedores')], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_telefono',
            field=models.CharField(blank=True, help_text='Formato recomendado: +5959xxxxxxx', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato recomendado: +5959xxxxxxx', regex='^\\+?595[0-9]{7,9}$')], verbose_name='Teléfono de contacto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_fantasia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Correo inválido')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(max_length=150, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(error_messages={'unique': 'Ya existe un proveedor con este RUC.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Ej. 1234567-8', regex='^[0-9]{5,12}(-[0-9]{1})?$')], verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(error_messages={'blank': 'Debe ingresar un número de teléfono.', 'required': 'Debe ingresar un número de teléfono.'}, help_text='Formato recomendado: +5959xxxxxxx', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato recomendado: +5959xxxxxxx', regex='^\\+?595[0-9]{7,9}$')], verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='NotificacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proveedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación de Proveedor',
                'verbose_name_plural': 'Preferencias de Notificación de Proveedor',
            },
        ),
    ]
