# Generated by Django 5.2.5 on 2025-09-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
