# Generated by Django 5.2.5 on 2025-10-01 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_proveedor_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(help_text='Formato recomendado: +5959xxxxxxx', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato recomendado: +5959xxxxxxx', regex='^\\+?595[0-9]{7,9}$')], verbose_name='Teléfono'),
        ),
    ]
