# Generated by Django 5.2.5 on 2025-10-25 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0004_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(error_messages={'unique': 'Ya existe un proveedor con este RUC.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Ej. 80012345-1', regex='^[0-9]{5,12}(-[0-9]{1})?$')], verbose_name='RUC'),
        ),
    ]
