# Generated by Django 5.2.5 on 2025-10-15 08:53

import django.core.validators
import presupuesto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
        ('servicio', '0007_alter_servicio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='servicios',
            field=models.ManyToManyField(through='presupuesto.PresupuestoServicio', to='servicio.servicio', verbose_name='Servicios a realizar'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha_vencimiento',
            field=models.DateField(default=presupuesto.models.default_fecha_vencimiento, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='presupuestoservicio',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, error_messages={'invalid': 'Ingrese un número válido', 'min_value': 'Cantidad debe ser mayor a 0.00', 'required': 'Este campo es obligatorio'}, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad'),
        ),
    ]
