# Generated by Django 5.2.5 on 2025-10-16 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_presupuesto_servicios_and_more'),
        ('servicio', '0007_alter_servicio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoservicio',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.presupuesto', verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='presupuestoservicio',
            name='servicio',
            field=models.ForeignKey(error_messages={'blank': 'Este campo es obligatorio', 'null': 'Este campo es obligatorio'}, on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio', verbose_name='Servicio'),
        ),
    ]
