# Generated by Django 5.2.5 on 2025-10-18 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_alter_cliente_numero_documento'),
        ('presupuesto', '0003_alter_presupuestoservicio_presupuesto_and_more'),
        ('servicio', '0009_alter_servicio_mano_obra'),
        ('vehiculo', '0006_alter_vehiculo_tipo_combustible_alter_vehiculo_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='cliente',
            field=models.ForeignKey(error_messages={'blank': 'Este campo es obligatorio.', 'null': 'Este campo es obligatorio.'}, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='vehiculo',
            field=models.ForeignKey(error_messages={'blank': 'Este campo es obligatorio.', 'null': 'Este campo es obligatorio.'}, help_text='Seleccione un vehículo por chapa', on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='presupuestoservicio',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, error_messages={'invalid': 'Ingrese un número válido', 'min_value': 'Cantidad debe ser mayor a 0.00', 'required': 'Este campo es obligatorio.'}, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='presupuestoservicio',
            name='servicio',
            field=models.ForeignKey(error_messages={'blank': 'Este campo es obligatorio.', 'null': 'Este campo es obligatorio.'}, on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio', verbose_name='Servicio'),
        ),
    ]
