# Generated by Django 5.2.5 on 2025-10-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0004_alter_presupuesto_cliente_alter_presupuesto_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
