# Generated by Django 5.2.5 on 2025-11-01 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0005_alter_presupuesto_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'ordering': ('-fecha_creacion',), 'permissions': [('gestionar_presupuestos', 'Puede gestionar presupuestos'), ('ver_presupuestos', 'Puede ver presupuestos'), ('agregar_presupuestos', 'Puede registrar presupuestos'), ('editar_presupuestos', 'Puede actualizar presupuestos'), ('cambiar_estado_presupuestos', 'Puede cambiar estado de presupuestos'), ('imprimir_presupuestos', 'Puede imprimir presupuestos')], 'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
    ]
