# Generated by Django 5.2.5 on 2025-11-04 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0007_alter_ordentrabajo_presupuesto_origen'),
        ('presupuesto', '0008_presupuesto_orden_trabajo_generada'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='orden_trabajo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuesto_asociado', to='orden_trabajo.ordentrabajo', verbose_name='Orden de trabajo generada'),
        ),
    ]
