# Generated by Django 5.2.5 on 2025-11-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0011_alter_presupuesto_iva_porcentaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='orden_trabajo_generada',
        ),
    ]
