# Generated by Django 5.2.5 on 2025-11-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0012_remove_presupuesto_orden_trabajo_generada'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='orden_trabajo_generada',
            field=models.BooleanField(default=False, help_text='Indica si ya se generó una orden de trabajo desde este presupuesto', verbose_name='Orden de trabajo generada'),
        ),
    ]
