# Generated by Django 5.2.5 on 2025-11-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0013_presupuesto_orden_trabajo_generada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='iva_porcentaje',
            field=models.DecimalField(choices=[(10, '10% - Con IVA'), (5, '5% - Con IVA'), (0, '0% - Sin IVA')], decimal_places=2, default=10, help_text='Porcentaje de IVA aplicable', max_digits=5, verbose_name='IVA %'),
        ),
    ]
