# Generated by Django 5.2.5 on 2025-12-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0014_alter_presupuesto_iva_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='iva_porcentaje',
            field=models.DecimalField(choices=[(10, '10% - Con IVA'), (5, '5% - Con IVA'), (0, '0% - Sin IVA')], decimal_places=2, help_text='Porcentaje de IVA aplicable', max_digits=5, verbose_name='IVA %'),
        ),
    ]
