# Generated by Django 5.2.5 on 2026-01-16 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0017_alter_presupuesto_iva_porcentaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('evento', models.CharField(max_length=120, verbose_name='Evento')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('Presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='presupuesto.presupuesto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Bitácora de Presupuesto',
                'verbose_name_plural': 'Bitácora de Presupuesto',
                'ordering': ('-fecha',),
            },
        ),
    ]
