# Generated by Django 5.2.5 on 2026-01-16 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0018_bitacorapresupuesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacorapresupuesto',
            old_name='Presupuesto',
            new_name='presupuesto',
        ),
    ]
