# Generated by Django 5.2.5 on 2026-02-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0019_rename_presupuesto_bitacorapresupuesto_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='iva_porcentaje',
            field=models.DecimalField(choices=[('10.00', '10% - Con IVA'), ('5.00', '5% - Con IVA'), ('0.00', '0% - Sin IVA')], decimal_places=2, default='10.00', help_text='Porcentaje de IVA aplicable', max_digits=5, verbose_name='IVA %'),
        ),
    ]
