# Generated by Django 5.2.5 on 2026-06-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['-fecha_apertura'], 'permissions': [('ver_finanzas', 'Puede ver finanzas'), ('gestionar_finanzas', 'Puede gestionar finanzas'), ('abrir_caja', 'Puede abrir caja'), ('cerrar_caja', 'Puede cerrar caja'), ('ver_reportes_financieros', 'Puede ver reportes financieros')], 'verbose_name': 'Finanza', 'verbose_name_plural': 'Finanzas'},
        ),
    ]
