# Generated by Django 5.2.5 on 2026-07-07 16:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanza', '0004_caja_sucursal_cobro_sucursal_cuentacobrar_sucursal_and_more'),
        ('sucursal', '0002_backfill_sucursal_existente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='medio_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('banco', 'Banco'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20, verbose_name='Medio de pago'),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='medio_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('banco', 'Banco'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20, verbose_name='Medio de pago'),
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='medio_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('banco', 'Banco'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20, verbose_name='Medio de pago'),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='origen',
            field=models.CharField(choices=[('factura', 'Factura'), ('compra', 'Compra'), ('gasto', 'Gasto'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ande', 'ANDE'), ('essap', 'ESSAP'), ('tigo', 'Tigo'), ('claro', 'Claro'), ('internet', 'Internet'), ('alquiler', 'Alquiler'), ('sueldo', 'Sueldo'), ('ips', 'IPS'), ('iva', 'IVA'), ('municipalidad', 'Municipalidad'), ('combustible', 'Combustible'), ('papeleria', 'Papelería'), ('limpieza', 'Limpieza'), ('viatico', 'Viático'), ('refrigerio', 'Refrigerio'), ('mantenimiento', 'Mantenimiento'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de gasto')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor / Entidad')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal', verbose_name='Sucursal')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanza.gasto', verbose_name='Gasto'),
        ),
        migrations.CreateModel(
            name='PagoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('banco', 'Banco'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20, verbose_name='Medio de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanza.caja', verbose_name='Caja')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanza.gasto')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal', verbose_name='Sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Gasto',
                'verbose_name_plural': 'Pagos de Gastos',
                'ordering': ['-fecha'],
            },
        ),
    ]
