# Generated by Django 5.2.5 on 2025-09-10 02:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CI_PY', 'Cédula paraguaya'), ('RUC', 'Registro Único de Contribuyente'), ('PAS', 'Pasaporte'), ('OTRO', 'Otro documento')], max_length=10, verbose_name='Tipo Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Ej.: 1234567 o 80012345-6', regex='^[0-9]{5,12}(-[0-9]{1})?$')])),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato recomendado: +5959xxxxxxx', regex='^\\+?595[0-9]{7,9}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Correo inválido')])),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('-fecha_registro',),
                'permissions': [('gestionar_clientes', 'Puede gestionar clientes'), ('ver_clientes', 'Puede ver clientes'), ('agregar_clientes', 'Puede registrar clientes'), ('editar_clientes', 'Puede actualizar clientes'), ('desactivar_clientes', 'Puede desactivar clientes')],
            },
        ),
        migrations.CreateModel(
            name='NotificacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
            },
        ),
    ]
