# Generated by Django 5.2.5 on 2025-09-10 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Ej.: 1234567 o 1234567-8', regex='^[0-9]{5,12}(-[0-9]{1})?$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato recomendado: +595xxxxxxx', regex='^\\+?595[0-9]{7,9}$')]),
        ),
    ]
