# Generated by Django 5.2.5 on 2025-09-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_numero_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='activo',
            new_name='is_active',
        ),
    ]
