# Generated by Django 5.2.5 on 2025-09-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_rename_activo_cliente_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_constitucion',
            field=models.DateField(blank=True, help_text='Requerida si es Persona Jurídica', null=True, verbose_name='Fecha de constitución'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Requerida si es Persona Física', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('FISICA', 'Persona Física'), ('JURIDICA', 'Persona Jurídica')], default='FISICA', help_text='Seleccione si es Persona Física o Persona Jurídica', max_length=10, verbose_name='Tipo de cliente'),
        ),
    ]
