# Generated by Django 5.2.5 on 2025-09-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_fecha_constitucion_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('fisica', 'Persona Física'), ('juridica', 'Persona Jurídica')], default='fisica', help_text='Seleccione si es Persona Física o Persona Jurídica', max_length=10, verbose_name='Tipo de cliente'),
        ),
    ]
