# Generated by Django 5.2.5 on 2025-09-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CI_PY', 'Cédula Paraguaya'), ('RUC', 'Registro Único de Contribuyente'), ('PAS', 'Pasaporte'), ('OTRO', 'Otro documento')], max_length=10, verbose_name='Tipo Documento'),
        ),
    ]
