# Generated by Django 5.2.5 on 2025-09-11 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_cliente_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=5950000000, error_messages={'blank': 'Debe ingresar un número de teléfono.', 'required': 'Debe ingresar un número de teléfono.'}, help_text='Formato recomendado: +5959xxxxxxx', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato recomendado: +595xxxxxxx', regex='^\\+?595[0-9]{7,9}$')], verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
