# Generated by Django 5.2.5 on 2025-09-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_constitucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de constitución'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('fisica', 'Persona Física'), ('juridica', 'Persona Jurídica')], default='fisica', max_length=10, verbose_name='Tipo de cliente'),
        ),
    ]
