# Generated by Django 5.2.5 on 2025-10-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_alter_cliente_fecha_constitucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
