# Generated by Django 5.2.5 on 2025-11-01 04:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0009_alter_cliente_numero_documento'),
        ('empleado', '0003_alter_empleado_cedula_ruc'),
        ('presupuesto', '0005_alter_presupuesto_estado'),
        ('servicio', '0012_alter_servicio_comision_porcentaje'),
        ('vehiculo', '0007_alter_vehiculo_nro_chapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio unitario')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Servicio de la orden',
                'verbose_name_plural': 'Servicios de la orden',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Observaciones')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('subtotal_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal servicios')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
                ('presupuesto_origen', models.ForeignKey(blank=True, help_text='Se completa cuando la OT se genera desde un presupuesto confirmado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuesto.presupuesto', verbose_name='Presupuesto de origen')),
                ('servicios', models.ManyToManyField(through='orden_trabajo.OrdenServicio', to='servicio.servicio', verbose_name='Servicios')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculo.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ('-fecha_creacion',),
                'permissions': [('gestionar_ordenes', 'Puede gestionar órdenes de trabajo'), ('ver_ordenes', 'Puede ver órdenes de trabajo'), ('agregar_ordenes', 'Puede registrar órdenes de trabajo'), ('editar_ordenes', 'Puede actualizar órdenes de trabajo'), ('finalizar_ordenes', 'Puede finalizar órdenes de trabajo'), ('cambiar_estado_ordenes', 'Puede cambiar estado de órdenes de trabajo')],
            },
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_trabajo.ordentrabajo', verbose_name='Orden'),
        ),
        migrations.CreateModel(
            name='BitacoraOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('evento', models.CharField(max_length=120, verbose_name='Evento')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='orden_trabajo.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Bitácora de Orden',
                'verbose_name_plural': 'Bitácora de Orden',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='AsignacionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('en_ejecucion', 'En Ejecución'), ('liberado', 'Liberado')], default='asignado', max_length=20, verbose_name='Estado')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('fecha_liberacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de liberación')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='empleado.empleado', verbose_name='Empleado')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='orden_trabajo.ordentrabajo', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Asignación de Orden',
                'verbose_name_plural': 'Asignaciones de Orden',
            },
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='orden_traba_estado_74719b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['fecha_creacion'], name='orden_traba_fecha_c_f2909e_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenservicio',
            index=models.Index(fields=['orden'], name='orden_traba_orden_i_036f44_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenservicio',
            index=models.Index(fields=['servicio'], name='orden_traba_servici_345113_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordenservicio',
            constraint=models.UniqueConstraint(fields=('orden', 'servicio'), name='uq_orden_servicio'),
        ),
        migrations.AddConstraint(
            model_name='ordenservicio',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_os_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='ordenservicio',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='ck_os_precio_gte_0'),
        ),
        migrations.AddIndex(
            model_name='asignacionorden',
            index=models.Index(fields=['empleado', 'estado'], name='orden_traba_emplead_e6f774_idx'),
        ),
    ]
