# Generated by Django 5.2.5 on 2025-11-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ('-fecha_creacion',), 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('espera_repuestos', 'Espera Repuestos'), ('en_proceso', 'En Proceso'), ('pausado', 'Pausad'), ('completado', 'Completado'), ('facturado', 'Facturado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
