# Generated by Django 5.2.5 on 2025-11-01 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_alter_empleado_cedula_ruc'),
        ('orden_trabajo', '0002_alter_ordentrabajo_options_alter_ordentrabajo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionorden',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orden_trabajo.ordenservicio'),
        ),
        migrations.AlterField(
            model_name='asignacionorden',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado'),
        ),
    ]
