# Generated by Django 5.2.5 on 2025-11-01 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_alter_empleado_cedula_ruc'),
        ('orden_trabajo', '0003_asignacionorden_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionorden',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado'),
        ),
    ]
