# Generated by Django 5.2.5 on 2025-11-01 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_alter_empleado_cedula_ruc'),
        ('orden_trabajo', '0004_alter_asignacionorden_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionorden',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='empleado.empleado', verbose_name='Empleado'),
        ),
    ]
