# Generated by Django 5.2.5 on 2025-11-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0005_alter_asignacionorden_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ('-fecha_creacion',), 'permissions': [('gestionar_ordenes_trabajo', 'Puede gestionar órdenes de trabajo'), ('ver_ordenes_trabajo', 'Puede ver órdenes de trabajo'), ('agregar_ordenes_trabajo', 'Puede registrar órdenes de trabajo'), ('editar_ordenes_trabajo', 'Puede actualizar órdenes de trabajo'), ('cambiar_estado_ordenes_trabajo', 'Puede cambiar el estado de órdenes de trabajo'), ('imprimir_ordenes_trabajo', 'Puede imprimir órdenes de trabajo')], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('espera_repuestos', 'Espera Repuestos'), ('en_proceso', 'En Proceso'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('facturado', 'Facturado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
