# Generated by Django 5.2.5 on 2025-11-04 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0006_alter_ordentrabajo_options_alter_ordentrabajo_estado'),
        ('presupuesto', '0008_presupuesto_orden_trabajo_generada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='presupuesto_origen',
            field=models.ForeignKey(blank=True, help_text='Se completa cuando la OT se genera desde un presupuesto confirmado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='presupuesto.presupuesto', verbose_name='Presupuesto de origen'),
        ),
    ]
