# Generated by Django 5.2.5 on 2025-11-04 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0008_ordentrabajo_factura_generada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de descuento en guaraníes', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='iva_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto IVA'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='iva_porcentaje',
            field=models.DecimalField(choices=[(10, '10% - Con IVA'), (5, '5% - Con IVA'), (0, '0% - Sin IVA')], decimal_places=2, default=10, help_text='Porcentaje de IVA aplicable', max_digits=5, verbose_name='IVA %'),
        ),
    ]
