# Generated by Django 5.2.5 on 2025-11-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0009_ordentrabajo_descuento_ordentrabajo_iva_monto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='factura_generada',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='iva_monto',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='iva_porcentaje',
        ),
    ]
