# Generated by Django 5.2.5 on 2025-11-04 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_remove_factura_factura_generada_desde_orden_and_more'),
        ('orden_trabajo', '0010_remove_ordentrabajo_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_trabajo', to='factura.factura'),
        ),
    ]
