# Generated by Django 5.2.5 on 2025-11-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0011_ordentrabajo_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='factura_generada',
            field=models.BooleanField(default=False, help_text='Indica si ya se generó una factura desde esta orden', verbose_name='Factura generada'),
        ),
    ]
