# Generated by Django 5.2.5 on 2025-11-05 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_empleado_limite_horas_diarias'),
        ('orden_trabajo', '0013_ordentrabajo_descuento_ordentrabajo_iva_monto_and_more'),
        ('servicio', '0014_alter_servicioinsumo_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTiempoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('tiempo_minutos', models.PositiveIntegerField(verbose_name='Tiempo en minutos')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado', verbose_name='Empleado')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_trabajo.ordentrabajo', verbose_name='Orden de trabajo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Registro de tiempo empleado',
                'verbose_name_plural': 'Registros de tiempo empleados',
                'ordering': ('-fecha', 'empleado'),
            },
        ),
    ]
