# Generated by Django 5.2.5 on 2026-03-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0014_registrotiempoempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='empleado_finalizado',
            field=models.BooleanField(default=False, help_text='Indica si el empleado marcó este servicio como finalizado', verbose_name='Finalizado por empleado'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='fecha_finalizacion_empleado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización (empleado)'),
        ),
    ]
