# Generated by Django 5.2.5 on 2026-03-25 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_alter_empleado_limite_horas_diarias'),
        ('orden_trabajo', '0015_ordenservicio_empleado_finalizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTiempoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Momento en que el empleado comenzó a trabajar en este servicio', null=True, verbose_name='Fecha/Hora de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Momento en que el empleado terminó de trabajar en este servicio', null=True, verbose_name='Fecha/Hora de fin')),
                ('minutos_trabajados', models.PositiveIntegerField(default=0, help_text='Calculado automáticamente al finalizar', verbose_name='Minutos trabajados')),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('pausado', 'Pausado')], default='en_curso', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado', verbose_name='Empleado')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_trabajo.ordentrabajo', verbose_name='Orden de trabajo')),
                ('servicio_orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orden_trabajo.ordenservicio', verbose_name='Servicio de orden')),
            ],
            options={
                'verbose_name': 'Registro de tiempo real',
                'verbose_name_plural': 'Registros de tiempo real',
                'ordering': ('-fecha_inicio',),
            },
        ),
        migrations.DeleteModel(
            name='RegistroTiempoEmpleado',
        ),
    ]
