# Generated by Django 5.2.5 on 2026-03-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0017_asignacionorden_registro_tiempo_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotiemporeal',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de fin'),
        ),
        migrations.AlterField(
            model_name='registrotiemporeal',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='registrotiemporeal',
            name='minutos_trabajados',
            field=models.PositiveIntegerField(default=0, verbose_name='Minutos trabajados'),
        ),
    ]
