# Generated by Django 5.2.5 on 2026-03-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0018_alter_registrotiemporeal_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionorden',
            name='registro_tiempo_real',
        ),
    ]
