# Generated by Django 5.2.5 on 2026-03-25 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0019_remove_asignacionorden_registro_tiempo_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionorden',
            name='registro_tiempo_real',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignacion', to='orden_trabajo.registrotiemporeal'),
        ),
    ]
