# Generated by Django 5.2.5 on 2026-04-05 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0020_asignacionorden_registro_tiempo_real'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('espera_repuestos', 'Espera Repuestos'), ('en_proceso', 'En Proceso'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('facturado', 'Facturado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='RevisionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de la revisión')),
                ('observaciones', models.TextField(blank=True, help_text='Motivo del rechazo o comentarios de aprobación', null=True, verbose_name='Observaciones')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de revisión')),
                ('orden_servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='orden_trabajo.ordenservicio', verbose_name='Servicio en revisión')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la revisión')),
            ],
            options={
                'verbose_name': 'Revisión de servicio',
                'verbose_name_plural': 'Revisiones de servicios',
            },
        ),
    ]
