# Generated by Django 5.2.5 on 2026-04-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0021_alter_ordentrabajo_estado_revisionservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('espera_repuestos', 'Espera Repuestos'), ('en_proceso', 'En Proceso'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('facturado', 'Facturado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='RevisionServicio',
        ),
    ]
