# Generated by Django 5.2.5 on 2026-04-09 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0022_alter_ordentrabajo_estado_delete_revisionservicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='modificado_despues_rechazo',
            field=models.BooleanField(default=False, help_text='Indica si este servicio fue modificado luego de ser rechazado en revisión', verbose_name='Modificado después de rechazo'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('espera_repuestos', 'Espera Repuestos'), ('en_proceso', 'En Proceso'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('facturado', 'Facturado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='RevisionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False, help_text='True = aprobado, False = rechazado', verbose_name='Aprobado')),
                ('observacion', models.TextField(blank=True, help_text='Motivo del rechazo o comentario de la revisión', null=True, verbose_name='Observación')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de revisión')),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='orden_trabajo.ordenservicio', verbose_name='Servicio revisado')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_servicios', to='orden_trabajo.ordentrabajo', verbose_name='Orden de trabajo')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Revisión de servicio',
                'verbose_name_plural': 'Revisiones de servicios',
                'unique_together': {('orden_servicio', 'orden_trabajo')},
            },
        ),
    ]
