# Generated by Django 5.2.5 on 2026-04-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0023_ordenservicio_modificado_despues_rechazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='insumos_descontados',
            field=models.BooleanField(default=False, help_text='Indica si ya se descontaron los insumos de este servicio del stock', verbose_name='Insumos descontados'),
        ),
    ]
