# Generated by Django 5.2.5 on 2026-05-20 01:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumo', '0015_insumo_garantia_meses_insumo_tiene_garantia_and_more'),
        ('proveedor', '0005_alter_proveedor_ruc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('numero_factura', models.CharField(blank=True, default='', max_length=30)),
                ('condicion_compra', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('total_iva', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('total_general', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=10)),
                ('stock_actualizado', models.BooleanField(default=False)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra_creada', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='proveedor.proveedor')),
                ('usuario_anulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra_anulada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ('-fecha', '-id'),
                'permissions': [('gestionar_compra', 'Puede gestionar compras'), ('ver_compra', 'Puede ver compras'), ('agregar_compra', 'Puede registrar compras'), ('anular_compra', 'Puede anular compras'), ('imprimir_compra', 'Puede imprimir compras')],
            },
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('iva', models.PositiveSmallIntegerField(choices=[(10, '10%'), (5, '5%'), (0, 'Exento')], default=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compra.compra')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compra_detalle', to='insumo.insumo')),
            ],
            options={
                'verbose_name': 'Detalle de compra',
                'verbose_name_plural': 'Detalles de compra',
            },
        ),
    ]
