# Generated by Django 5.2.5 on 2026-05-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ('-fecha', '-id'), 'permissions': [('gestionar_compras', 'Puede gestionar compras'), ('ver_compras', 'Puede ver compras'), ('agregar_compras', 'Puede registrar compras'), ('anular_compras', 'Puede anular compras'), ('imprimir_compras', 'Puede imprimir compras')], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
