# Generated by Django 5.2.5 on 2026-05-28 00:37

import compra.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_alter_compra_options'),
        ('insumo', '0015_insumo_garantia_meses_insumo_tiene_garantia_and_more'),
        ('proveedor', '0005_alter_proveedor_ruc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ('-fecha_emision',), 'permissions': [('ver_compras', 'Puede ver compras'), ('agregar_compras', 'Puede agregar compras'), ('editar_compras', 'Puede editar compras'), ('imprimir_compras', 'Puede imprimir compras'), ('recibir_compras', 'Puede recibir compras')], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='condicion_compra',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha_anulacion',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='motivo_anulacion',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='numero_factura',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='stock_actualizado',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='total_general',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='total_iva',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='usuario_anulacion',
        ),
        migrations.AddField(
            model_name='compra',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='compra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='compra',
            name='entrada_almacen_generada',
            field=models.BooleanField(default=False, verbose_name='Entrada generada'),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha emisión'),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_entrega_esperada',
            field=models.DateField(default=compra.models.default_fecha_entrega_esperada, verbose_name='Fecha entrega esperada'),
        ),
        migrations.AddField(
            model_name='compra',
            name='iva_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='compra',
            name='iva_porcentaje',
            field=models.DecimalField(choices=[(Decimal('10.00'), '10%'), (Decimal('5.00'), '5%'), (Decimal('0.00'), '0%')], decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='IVA %'),
        ),
        migrations.AddField(
            model_name='compra',
            name='subtotal_productos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='BitacoraCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evento', models.CharField(max_length=120)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='compra.compra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de Compra',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compra.compra', verbose_name='Orden de Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto de Compra',
                'verbose_name_plural': 'Productos de Compra',
                'unique_together': {('compra', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='productos',
            field=models.ManyToManyField(through='compra.CompraProducto', to='insumo.insumo', verbose_name='Productos'),
        ),
        migrations.DeleteModel(
            name='CompraDetalle',
        ),
    ]
