# Generated by Django 5.2.5 on 2026-05-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_alter_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='condicion_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10, verbose_name='Condición de Pago'),
        ),
    ]
