# Generated by Django 5.2.5 on 2026-05-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_compra_condicion_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='factura_pdf',
            field=models.FileField(blank=True, null=True, upload_to='compras/facturas/', verbose_name='Factura PDF'),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha recepción'),
        ),
        migrations.AddField(
            model_name='compra',
            name='observaciones_recepcion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de recepción'),
        ),
    ]
