# Generated by Django 5.2.5 on 2026-05-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_compra_factura_pdf_compra_fecha_recepcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='factura_pdf',
            field=models.FileField(blank=True, null=True, upload_to='compra/facturas-recibos/', verbose_name='Factura PDF'),
        ),
    ]
