# Generated by Django 5.2.5 on 2026-05-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0008_alter_compra_factura_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='factura_pdf',
            field=models.FileField(blank=True, null=True, upload_to='compra/factura/', verbose_name='Factura PDF'),
        ),
    ]
