# Generated by Django 5.2.5 on 2026-06-10 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0009_alter_compra_factura_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraproducto',
            name='cantidad_recibida',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad recibida', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Recibida'),
        ),
    ]
