# Generated by Django 5.2.5 on 2026-06-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0010_compraproducto_cantidad_recibida'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraproducto',
            name='observacion',
            field=models.TextField(blank=True, help_text='Observación sobre la recepción de este producto', null=True, verbose_name='Observación'),
        ),
    ]
