# Generated by Django 5.2.5 on 2025-11-01 04:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0012_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(default='001', max_length=3, verbose_name='Estab.')),
                ('punto_emision', models.CharField(default='001', max_length=3, verbose_name='Punto')),
                ('timbrado', models.CharField(blank=True, default='', max_length=20, verbose_name='Timbrado')),
                ('numero', models.IntegerField(default=0, verbose_name='Número correlativo')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('iva', models.PositiveSmallIntegerField(choices=[(10, '10%'), (4, '4%')], default=10, verbose_name='IVA')),
                ('sin_ot', models.BooleanField(default=False, verbose_name='Factura sin OT')),
                ('numero_ot', models.CharField(blank=True, default='', max_length=30, verbose_name='N° de OT (opcional)')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Subtotal')),
                ('total_iva', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total IVA')),
                ('total_general', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=10, verbose_name='Estado')),
                ('entregada', models.BooleanField(default=False, verbose_name='Entregada al cliente')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('configuracion_impresion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='seguridad.configuracionsistema', verbose_name='Configuración de impresión')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ('-fecha', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FacturaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Insumo')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio unitario')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='factura.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de Insumo',
                'verbose_name_plural': 'Detalles de Insumo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FacturaSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(max_length=3)),
                ('punto_emision', models.CharField(max_length=3)),
                ('timbrado', models.CharField(blank=True, default='', max_length=20)),
                ('ultimo_numero', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serie de Facturación',
                'verbose_name_plural': 'Series de Facturación',
                'unique_together': {('establecimiento', 'punto_emision', 'timbrado')},
            },
        ),
        migrations.CreateModel(
            name='FacturaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Servicio')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio unitario')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='factura.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de Servicio',
                'verbose_name_plural': 'Detalles de Servicio',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha'], name='factura_fac_fecha_62d835_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['establecimiento', 'punto_emision', 'timbrado', 'numero'], name='factura_fac_estable_534907_idx'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(fields=('establecimiento', 'punto_emision', 'timbrado', 'numero'), name='uniq_factura_serie_correlativo'),
        ),
    ]
