# Generated by Django 5.2.5 on 2025-11-04 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
        ('orden_trabajo', '0008_ordentrabajo_factura_generada'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='factura_generada_desde_orden',
            field=models.BooleanField(default=False, help_text='Indica si esta factura se generó desde una orden de trabajo', verbose_name='Factura generada desde orden'),
        ),
        migrations.AddField(
            model_name='factura',
            name='orden_trabajo',
            field=models.OneToOneField(blank=True, help_text='Orden de trabajo desde la cual se generó esta factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_asociada', to='orden_trabajo.ordentrabajo', verbose_name='Orden de trabajo asociada'),
        ),
    ]
