# Generated by Django 5.2.5 on 2025-11-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_factura_factura_generada_desde_orden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='factura_generada_desde_orden',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='orden_trabajo',
        ),
    ]
