# Generated by Django 5.2.5 on 2025-11-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_remove_factura_factura_generada_desde_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente_direccion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_nombre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre/Razón Social'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_ruc',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RUC'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_telefono',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='factura',
            name='condicion_venta',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10, verbose_name='Condición de Venta'),
        ),
    ]
