# Generated by Django 5.2.5 on 2026-03-20 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_factura_cliente_direccion_factura_cliente_nombre_and_more'),
        ('seguridad', '0012_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ('-fecha', '-id')},
        ),
        migrations.AlterModelOptions(
            name='facturainsumo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='facturaservicio',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='factura',
            name='uniq_factura_serie_correlativo',
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='factura_fac_estable_534907_idx',
        ),
        migrations.AddField(
            model_name='factura',
            name='cdc',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='CDC'),
        ),
        migrations.AddField(
            model_name='factura',
            name='codigo_seguridad',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='Código seguridad'),
        ),
        migrations.AddField(
            model_name='factura',
            name='es_electronica',
            field=models.BooleanField(default=False, verbose_name='Factura electrónica'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_generacion_electronica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='qr',
            field=models.TextField(blank=True, default='', verbose_name='QR'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_documento',
            field=models.CharField(choices=[('01', 'Factura electrónica'), ('04', 'Autofactura electrónica'), ('05', 'Nota de crédito electrónica'), ('06', 'Nota de débito electrónica')], default='01', max_length=2, verbose_name='Tipo documento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='xml_generado',
            field=models.TextField(blank=True, default='', verbose_name='XML'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='configuracion_impresion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='seguridad.configuracionsistema', verbose_name='Configuración impresión'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='entregada',
            field=models.BooleanField(default=False, verbose_name='Entregada'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.PositiveSmallIntegerField(choices=[(10, '10%'), (5, '5%'), (0, 'Exento')], default=10, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_ot',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='N° de OT'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='factura',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente_ruc'], name='factura_fac_cliente_85ac13_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero'], name='factura_fac_numero_68d942_idx'),
        ),
    ]
