# Generated by Django 5.2.5 on 2026-03-27 03:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_alter_factura_options_alter_facturainsumo_options_and_more'),
        ('seguridad', '0012_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={},
        ),
        migrations.AlterModelOptions(
            name='facturainsumo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='facturaserie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='facturaservicio',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='factura_fac_fecha_62d835_idx',
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='factura_fac_cliente_85ac13_idx',
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='factura_fac_numero_68d942_idx',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='codigo_seguridad',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='es_electronica',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='xml_generado',
        ),
        migrations.AlterField(
            model_name='factura',
            name='cdc',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente_direccion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente_ruc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente_telefono',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='condicion_venta',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='configuracion_impresion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='seguridad.configuracionsistema'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='entregada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='establecimiento',
            field=models.CharField(default='001', max_length=3),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.PositiveSmallIntegerField(choices=[(10, '10%'), (5, '5%')], default=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_ot',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='factura',
            name='punto_emision',
            field=models.CharField(default='001', max_length=3),
        ),
        migrations.AlterField(
            model_name='factura',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_facturas/'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sin_ot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='timbrado',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_general',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_iva',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='facturainsumo',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='facturainsumo',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='facturainsumo',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='factura.factura'),
        ),
        migrations.AlterField(
            model_name='facturainsumo',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='facturaservicio',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='facturaservicio',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='facturaservicio',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='factura.factura'),
        ),
        migrations.AlterField(
            model_name='facturaservicio',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
