# Generated by Django 5.2.5 on 2026-04-21 23:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_alter_cliente_numero_documento'),
        ('factura', '0006_alter_factura_options_alter_facturainsumo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='cliente.cliente'),
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('establecimiento', models.CharField(default='001', max_length=3)),
                ('punto_emision', models.CharField(default='001', max_length=3)),
                ('timbrado', models.CharField(blank=True, default='', max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_general', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('motivo', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='factura.factura')),
            ],
        ),
    ]
