# Generated by Django 5.2.5 on 2026-04-22 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0008_alter_factura_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ('-fecha', '-id'), 'permissions': [('gestionar_facturas', 'Puede gestionar facturas'), ('ver_facturas', 'Puede ver facturas'), ('agregar_facturas', 'Puede emitir facturas'), ('editar_facturas', 'Puede actualizar facturas'), ('anular_facturas', 'Puede anular facturas'), ('imprimir_facturas', 'Puede imprimir facturas'), ('reimprimir_facturas', 'Puede reimprimir facturas'), ('ver_reportes_facturas', 'Puede ver reportes de facturas')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
