# Generated by Django 5.2.5 on 2026-04-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0009_alter_factura_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='motivo_anulacion',
            field=models.TextField(blank=True, help_text='Motivo obligatorio al anular la factura', null=True, verbose_name='Motivo de anulación'),
        ),
    ]
