# Generated by Django 5.2.5 on 2026-05-20 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0011_factura_usuario_anulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=12)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='factura.notacredito')),
            ],
        ),
    ]
