# Generated by Django 5.2.5 on 2026-05-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0012_notacreditodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_nota_credito',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se generó la Nota de Crédito', null=True, verbose_name='Fecha de Nota de Crédito'),
        ),
    ]
