# Generated by Django 5.2.5 on 2026-05-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0013_factura_fecha_nota_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='tipo',
            field=models.CharField(choices=[('TOTAL', 'Total'), ('PARCIAL', 'Parcial')], default='PARCIAL', help_text='Tipo de nota de crédito: TOTAL o PARCIAL', max_length=10),
        ),
    ]
