# Generated by Django 5.2.5 on 2026-05-20 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0014_notacredito_tipo'),
        ('insumo', '0015_insumo_garantia_meses_insumo_tiene_garantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturainsumo',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insumo.insumo'),
        ),
    ]
