# Generated by Django 5.2.5 on 2026-06-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0015_facturainsumo_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacredito',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10, verbose_name='Estado de la Nota'),
        ),
    ]
