# Generated by Django 5.2.5 on 2026-07-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0016_alter_notacredito_estado'),
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal', verbose_name='Sucursal'),
        ),
    ]
