# Generated by Django 5.2.5 on 2025-10-09 01:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ('nombre',), 'permissions': [('gestionar_insumos', 'Puede gestionar insumos'), ('ver_insumos', 'Puede ver insumos'), ('agregar_insumos', 'Puede registrar insumos'), ('editar_insumos', 'Puede actualizar insumos'), ('desactivar_insumos', 'Puede desactivar/activar insumos')], 'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.RenameField(
            model_name='insumo',
            old_name='activo',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(blank=True, help_text='Ej.: Lubricantes, Filtros, Frenos, Motor.', max_length=100, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Existencia actual (no puede ser negativa).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en stock'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Costo por unidad en Gs. (>= 0).', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo unitario'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detalle breve del insumo (opcional).', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(help_text='Ej.: Filtro de aceite, Aceite 10W40, Pastilla de freno…', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['nombre'], name='insumo_insu_nombre_ce68d8_idx'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['categoria'], name='insumo_insu_categor_0285c7_idx'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['is_active'], name='insumo_insu_is_acti_4cfcc0_idx'),
        ),
    ]
