# Generated by Django 5.2.5 on 2025-10-09 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_alter_insumo_options_rename_activo_insumo_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
    ]
