# Generated by Django 5.2.5 on 2025-10-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0003_insumo_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detalle breve del insumo.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(choices=[('UN', 'Unidad'), ('KG', 'Kilogramo'), ('LT', 'Litro'), ('MT', 'Metro'), ('CJ', 'Caja'), ('PA', 'Par'), ('OT', 'Otro')], default='UN', max_length=2, verbose_name='Unidad'),
        ),
    ]
