# Generated by Django 5.2.5 on 2025-10-11 04:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0004_alter_insumo_descripcion_alter_insumo_unidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad disponible en inventario', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock actual'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad mínima para alertas', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Existencia actual (no puede ser negativa).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad actual'),
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, verbose_name='Tipo de movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad')),
                ('motivo', models.CharField(choices=[('compra', 'Compra'), ('ajuste', 'Ajuste de inventario'), ('produccion', 'Producción'), ('venta', 'Venta/Servicio'), ('danado', 'Dañado/Perdido'), ('devolucion', 'Devolución'), ('otros', 'Otros')], default='ajuste', max_length=20, verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True, help_text='Detalles adicionales del movimiento', null=True, verbose_name='Observaciones')),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock anterior')),
                ('stock_posterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock posterior')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de movimiento')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo', verbose_name='Insumo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ('-fecha_movimiento',),
            },
        ),
    ]
