# Generated by Django 5.2.5 on 2025-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0006_remove_insumo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(choices=[('UN', 'UNIDAD'), ('KG', 'KILOGRAMO'), ('LT', 'LITRO'), ('MT', 'METRO'), ('CJ', 'CAJA'), ('PA', 'PAR'), ('OT', 'OTRO')], default='UN', max_length=2, verbose_name='Unidad'),
        ),
    ]
