# Generated by Django 5.2.5 on 2025-10-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0007_alter_insumo_unidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ('nombre',), 'permissions': [('gestionar_insumos', 'Puede gestionar insumos'), ('agregar_insumos', 'Puede agregar insumos'), ('ver_insumos', 'Puede ver insumos'), ('editar_insumos', 'Puede actualizar insumos'), ('desactivar_insumos', 'Puede desactivar/activar insumos'), ('gestionar_stock_insumos', 'Puede gestionar el stock de insumos')], 'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
    ]
