# Generated by Django 5.2.5 on 2025-10-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0008_alter_insumo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Costo por unidad en Gs. (>= 0).', max_digits=14, verbose_name='Costo unitario'),
        ),
    ]
