# Generated by Django 5.2.5 on 2025-10-22 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0009_alter_insumo_costo_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad disponible en inventario', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad mínima para alertas', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo'),
        ),
    ]
