# Generated by Django 5.2.5 on 2025-10-30 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0010_alter_insumo_stock_actual_alter_insumo_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='codigo_padre',
            field=models.ForeignKey(blank=True, help_text='Insumo principal al que pertenece este subinsumo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subinsumos', to='insumo.insumo', verbose_name='Insumo padre'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='es_subinsumo',
            field=models.BooleanField(default=False, help_text='Indica si es una unidad individual de un insumo principal', verbose_name='Es subinsumo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='numero_subinsumo',
            field=models.PositiveIntegerField(default=0, help_text='Número secuencial para subinsumos', verbose_name='Número de subinsumo'),
        ),
        migrations.AddConstraint(
            model_name='insumo',
            constraint=models.UniqueConstraint(fields=('codigo_padre', 'numero_subinsumo'), name='unique_subinsumo_number'),
        ),
    ]
