# Generated by Django 5.2.5 on 2025-10-30 09:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0011_insumo_codigo_padre_insumo_es_subinsumo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número secuencial para subinsumos (1, 2, 3, ...)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de subinsumo')),
                ('nombre', models.CharField(help_text='Nombre del subinsumo (puede ser igual al padre)', max_length=150, verbose_name='Nombre')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=1, help_text='Cantidad disponible para este subinsumo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock actual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'SubInsumo',
                'verbose_name_plural': 'SubInsumos',
                'ordering': ['insumo_padre', 'numero'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='insumo',
            name='unique_subinsumo_number',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='codigo_padre',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='es_subinsumo',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='numero_subinsumo',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(help_text='Ej.: Filtro de aceite, Aceite 10W40, Pastilla de freno…', max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='subinsumo',
            name='insumo_padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subinsumos', to='insumo.insumo', verbose_name='Insumo padre'),
        ),
        migrations.AddIndex(
            model_name='subinsumo',
            index=models.Index(fields=['insumo_padre', 'numero'], name='insumo_subi_insumo__3b5e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='subinsumo',
            index=models.Index(fields=['is_active'], name='insumo_subi_is_acti_47f381_idx'),
        ),
        migrations.AddConstraint(
            model_name='subinsumo',
            constraint=models.UniqueConstraint(fields=('insumo_padre', 'numero'), name='unique_subinsumo_number'),
        ),
    ]
