# Generated by Django 5.2.5 on 2026-03-27 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0012_subinsumo_remove_insumo_unique_subinsumo_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='grupo',
            field=models.CharField(choices=[('insumo', 'INSUMO (Material de trabajo)'), ('repuesto', 'REPUESTO (Parte para reparación)'), ('herramienta', 'HERRAMIENTA'), ('limpieza_mantenimiento', 'LIMPIEZA Y MANTENIMIENTO'), ('insumo_venta', 'INSUMO PARA VENTA')], default='insumo', help_text='Clasificación principal del insumo', max_length=30, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad disponible en inventario', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad mínima para alertas', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['grupo'], name='insumo_insu_grupo_ca9ad0_idx'),
        ),
    ]
