# Generated by Django 5.2.5 on 2026-03-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0013_insumo_grupo_alter_insumo_stock_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subinsumo',
            name='codigo_generado',
            field=models.CharField(blank=True, help_text='Código completo del subinsumo (ej: INS-0001-0001)', max_length=50, verbose_name='Código generado'),
        ),
        migrations.AddField(
            model_name='subinsumo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detalle breve del sub-insumo.', verbose_name='Descripción'),
        ),
        migrations.AddIndex(
            model_name='subinsumo',
            index=models.Index(fields=['codigo_generado'], name='insumo_subi_codigo__bb27af_idx'),
        ),
    ]
