# Generated by Django 5.2.5 on 2026-03-27 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0014_subinsumo_codigo_generado_subinsumo_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='garantia_meses',
            field=models.PositiveIntegerField(blank=True, help_text='Duración de la garantía en meses (1 a 12 meses)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Garantía (meses)'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='tiene_garantia',
            field=models.BooleanField(default=False, help_text='Indica si este repuesto tiene garantía', verbose_name='Tiene garantía'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['tiene_garantia'], name='insumo_insu_tiene_g_65575c_idx'),
        ),
    ]
