# Generated by Django 5.2.5 on 2025-09-10 06:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(error_messages={'blank': 'La clave es obligatoria.', 'unique': 'Ya existe una configuración con esa clave.'}, max_length=100, unique=True, verbose_name='Clave de configuración')),
                ('valor', models.TextField(error_messages={'blank': 'El valor es obligatorio.'}, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número'), ('boolean', 'Si/No'), ('email', 'Email'), ('json', 'JSON'), ('date', 'Fecha')], default='string', error_messages={'blank': 'El tipo es obligatorio.', 'invalid_choice': 'Tipo inválido.'}, max_length=10, verbose_name='Tipo de dato')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('grupo', models.CharField(default='general', max_length=50, verbose_name='Grupo')),
                ('editable', models.BooleanField(default=True, verbose_name='Editable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['grupo', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(error_messages={'blank': 'Debe seleccionar un rol.'}, max_length=50, verbose_name='Rol')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupos a los que pertenece este usuario.', related_name='seguridad_usuario_set', related_query_name='usuario', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='seguridad_usuario_permissions_set', related_query_name='usuario', to='auth.permission', verbose_name='Permisos de usuario')),
            ],
            options={
                'permissions': [('gestionar_usuarios', 'Puede gestionar usuarios'), ('ver_usuarios', 'Puede ver usuarios'), ('agregar_usuarios', 'Puede agregar usuarios'), ('editar_usuarios', 'Puede editar usuarios'), ('desactivar_usuarios', 'Puede desactivar/activar usuarios'), ('gestionar_roles', 'Puede gestionar roles y permisos'), ('ver_roles', 'Puede ver roles y permisos'), ('agregar_roles', 'Puede agregar roles y permisos'), ('editar_roles', 'Puede editar roles y permisos'), ('desactivar_roles', 'Puede desactivar roles y permisos'), ('gestionar_configuraciones', 'Puede gestionar configuraciones del sistema'), ('ver_configuraciones', 'Puede ver configuraciones del sistema'), ('agregar_configuraciones', 'Puede agregar configuraciones del sistema'), ('editar_configuraciones', 'Puede editar configuraciones del sistema'), ('desactivar_configuraciones', 'Puede desactivar/activar configuraciones del sistema'), ('gestionar_clientes', 'Puede gestionar clientes'), ('gestionar_vehiculos', 'Puede gestionar vehículos'), ('gestionar_ordenes', 'Puede gestionar órdenes de trabajo'), ('gestionar_proveedores', 'Puede gestionar proveedores'), ('gestionar_insumos', 'Puede gestionar insumos'), ('gestionar_finanzas', 'Puede gestionar finanzas')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('requiere_cambio_password', models.BooleanField(default=False)),
                ('ultimo_cambio_password', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
