# Generated by Django 5.2.5 on 2025-09-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='clave',
            field=models.CharField(error_messages={'unique': 'Ya existe una configuración con esa clave.'}, max_length=100, unique=True, verbose_name='Clave de configuración'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='tipo',
            field=models.CharField(choices=[('string', 'Texto'), ('integer', 'Número'), ('boolean', 'Si/No'), ('email', 'Email'), ('json', 'JSON'), ('date', 'Fecha')], default='string', error_messages={'invalid_choice': 'Tipo inválido.'}, max_length=10, verbose_name='Tipo de dato'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='valor',
            field=models.TextField(verbose_name='Valor'),
        ),
    ]
