# Generated by Django 5.2.5 on 2025-09-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_alter_configuracionsistema_clave_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('gestionar_usuarios', 'Puede gestionar usuarios'), ('ver_usuarios', 'Puede ver usuarios'), ('agregar_usuarios', 'Puede agregar usuarios'), ('editar_usuarios', 'Puede editar usuarios'), ('desactivar_usuarios', 'Puede desactivar/activar usuarios'), ('gestionar_roles', 'Puede gestionar roles y permisos'), ('ver_roles', 'Puede ver roles y permisos'), ('agregar_roles', 'Puede agregar roles y permisos'), ('editar_roles', 'Puede editar roles y permisos'), ('desactivar_roles', 'Puede desactivar roles y permisos'), ('gestionar_configuraciones', 'Puede gestionar configuraciones del sistema'), ('ver_configuraciones', 'Puede ver configuraciones del sistema'), ('agregar_configuraciones', 'Puede agregar configuraciones del sistema'), ('editar_configuraciones', 'Puede editar configuraciones del sistema'), ('desactivar_configuraciones', 'Puede desactivar/activar configuraciones del sistema'), ('gestionar_vehiculos', 'Puede gestionar vehículos'), ('gestionar_ordenes', 'Puede gestionar órdenes de trabajo'), ('gestionar_proveedores', 'Puede gestionar proveedores'), ('gestionar_insumos', 'Puede gestionar insumos'), ('gestionar_finanzas', 'Puede gestionar finanzas')]},
        ),
    ]
