# Generated by Django 5.2.5 on 2025-10-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0009_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
    ]
