# Generated by Django 5.2.5 on 2025-10-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0010_remove_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Formato: +5959XXXXXXX', max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
