# Generated by Django 5.2.5 on 2026-07-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0012_alter_usuario_email'),
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sucursal_activa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_activos', to='sucursal.sucursal', verbose_name='Sucursal activa'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sucursales_permitidas',
            field=models.ManyToManyField(blank=True, related_name='perfiles_permitidos', to='sucursal.sucursal', verbose_name='Sucursales permitidas'),
        ),
    ]
