# Generated by Django 5.2.5 on 2025-10-01 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(blank=True, max_length=80, null=True, verbose_name='Categoría')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio base')),
                ('tiempo_min_estimado', models.PositiveIntegerField(help_text='En minutos, ej.: 60 = 1 hora', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tiempo mínimo estimado (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ('nombre',),
                'permissions': [('gestionar_servicios', 'Puede gestionar servicios'), ('ver_servicios', 'Puede ver servicios'), ('agregar_servicios', 'Puede registrar servicios'), ('editar_servicios', 'Puede actualizar servicios'), ('desactivar_servicios', 'Puede desactivar/activar servicios')],
            },
        ),
    ]
