# Generated by Django 5.2.5 on 2025-10-01 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(blank=True, help_text='Ej. Mantenimiento, Frenos, Motor, Electricidad', max_length=80, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detalles breves del servicio.', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(help_text='Ej. Cambio de aceite, Alineación y balanceo', max_length=120, unique=True, verbose_name='Nombre del servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, help_text='Monto en guaraníes. Debe ser mayor a 0.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio base'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tiempo_min_estimado',
            field=models.PositiveIntegerField(help_text='En minutos (p. ej., 60 = 1 hora).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tiempo mínimo estimado'),
        ),
    ]
