# Generated by Django 5.2.5 on 2025-10-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_servicio_categoria_alter_servicio_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, help_text='Monto en guaraníes. Debe ser mayor a 0.', max_digits=12, verbose_name='Precio base'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tiempo_min_estimado',
            field=models.PositiveIntegerField(help_text='En minutos (Ej. 60 = 1 hora).', verbose_name='Tiempo mínimo estimado'),
        ),
    ]
