# Generated by Django 5.2.5 on 2025-10-09 07:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0003_insumo_fecha_registro'),
        ('servicio', '0003_alter_servicio_precio_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='costo_insumos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total calculado de todos los insumos', max_digits=12, verbose_name='Costo total de insumos'),
        ),
        migrations.CreateModel(
            name='ServicioInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
            ],
            options={
                'verbose_name': 'Insumo del servicio',
                'verbose_name_plural': 'Insumos del servicio',
                'unique_together': {('servicio', 'insumo')},
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='insumos',
            field=models.ManyToManyField(blank=True, through='servicio.ServicioInsumo', to='insumo.insumo', verbose_name='Insumos requeridos'),
        ),
    ]
