# Generated by Django 5.2.5 on 2025-10-10 04:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0004_alter_insumo_descripcion_alter_insumo_unidad'),
        ('servicio', '0004_servicio_costo_insumos_servicioinsumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioinsumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, error_messages={'invalid': 'Ingrese un número válido', 'min_value': 'Cantidad debe ser mayor a 0.00', 'required': 'Este campo es obligatorio'}, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='servicioinsumo',
            name='insumo',
            field=models.ForeignKey(error_messages={'blank': 'Este campo es obligatorio', 'null': 'Este campo es obligatorio'}, on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo'),
        ),
    ]
