# Generated by Django 5.2.5 on 2025-10-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_alter_servicioinsumo_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='precio_base',
        ),
        migrations.AddField(
            model_name='servicio',
            name='mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto en guaraníes. Debe ser mayor a 0.', max_digits=12, verbose_name='Mano de obra'),
            preserve_default=False,
        ),
    ]
