# Generated by Django 5.2.5 on 2025-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_remove_servicio_precio_base_servicio_mano_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(blank=True, help_text='Ej. MANTENIMIENTO, FRENOS, MOTOR, ELECTRICIDAD', max_length=80, null=True, verbose_name='Categoría'),
        ),
    ]
