# Generated by Django 5.2.5 on 2025-10-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0008_alter_insumo_options'),
        ('servicio', '0007_alter_servicio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(default=1, help_text='Ej. MANTENIMIENTO, FRENOS, MOTOR, ELECTRICIDAD', max_length=80, verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='insumos',
            field=models.ManyToManyField(through='servicio.ServicioInsumo', to='insumo.insumo', verbose_name='Insumos requeridos'),
        ),
    ]
