# Generated by Django 5.2.5 on 2025-10-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0008_alter_servicio_categoria_alter_servicio_insumos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='mano_obra',
            field=models.DecimalField(decimal_places=2, help_text='Monto en guaraníes. Debe ser mayor a 0.', max_digits=14, verbose_name='Mano de obra'),
        ),
    ]
