# Generated by Django 5.2.5 on 2025-10-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0009_alter_servicio_mano_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje de comisión para el empleado', max_digits=5),
        ),
    ]
