# Generated by Django 5.2.5 on 2025-11-05 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0012_alter_servicio_comision_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='comision_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, help_text='Porcentaje de comisión para el empleado', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
