# Generated by Django 5.2.5 on 2025-11-05 07:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0012_subinsumo_remove_insumo_unique_subinsumo_number_and_more'),
        ('servicio', '0013_alter_servicio_comision_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioinsumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, error_messages={'invalid': 'Ingrese un número válido.', 'min_value': 'Cantidad debe ser mayor a 0.00', 'required': 'Este campo es obligatorio.'}, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='servicioinsumo',
            name='insumo',
            field=models.ForeignKey(error_messages={'blank': 'Este campo es obligatorio.', 'null': 'Este campo es obligatorio.'}, on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo'),
        ),
    ]
