# Generated by Django 5.2.5 on 2026-07-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('establecimiento', models.CharField(default='001', max_length=3, verbose_name='Establecimiento SET')),
                ('punto_emision', models.CharField(default='001', max_length=3, verbose_name='Punto de emisión SET')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
    ]
