# Generated by Django 5.2.5 on 2025-09-24 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=80, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=120, verbose_name='Modelo')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026, message='El año no puede ser mayor a %(limit_value)s.')], verbose_name='Año')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('nro_chapa', models.CharField(error_messages={'unique': 'Ya existe un vehículo con esta chapa.'}, help_text='Ej.: ABC-123 o formato local equivalente.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de chapa inválido.', regex='^[A-Z0-9\\-\\.]{4,12}$')], verbose_name='Nro. de chapa')),
                ('nro_chasis', models.CharField(error_messages={'unique': 'Ya existe un vehículo con este número de chasis.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Número de chasis inválido.', regex='^[A-HJ-NPR-Z0-9]{11,17}$')], verbose_name='Nro. de chasis')),
                ('cantidad_puerta', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de puertas')),
                ('motor_cilindrada', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cilindrada del motor')),
                ('tipo_combustible', models.CharField(choices=[('NAFTA', 'Nafta/Gasolina'), ('DIESEL', 'Diésel'), ('ELECTRICO', 'Eléctrico'), ('HIBRIDO', 'Híbrido'), ('GNC', 'GNC')], max_length=15, verbose_name='Tipo de combustible')),
                ('uso', models.CharField(choices=[('PARTICULAR', 'Particular'), ('COMERCIAL', 'Comercial'), ('OFICIAL', 'Oficial')], max_length=15, verbose_name='Uso')),
                ('cedula_verde', models.BooleanField(default=False, verbose_name='Cédula verde')),
                ('via_importacion', models.CharField(choices=[('LOCAL', 'Compra local'), ('IMPORTADO', 'Importado'), ('REMATE', 'Remate'), ('DIPLOMATICO', 'Diplomático')], max_length=15, verbose_name='Vía de importación')),
                ('procedencia', models.CharField(choices=[('PY', 'Paraguay'), ('BR', 'Brasil'), ('AR', 'Argentina'), ('US', 'Estados Unidos'), ('JP', 'Japón'), ('KR', 'Corea'), ('EU', 'Europa'), ('OTRO', 'Otro')], max_length=10, verbose_name='Procedencia')),
                ('tipo_transmision', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática'), ('CVT', 'CVT'), ('SECUENCIAL', 'Secuencial/DCT')], max_length=15, verbose_name='Tipo de transmisión')),
                ('alarma', models.BooleanField(default=False, verbose_name='Alarma')),
                ('gps', models.BooleanField(default=False, verbose_name='GPS')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ('-fecha_registro',),
                'permissions': [('gestionar_vehiculos', 'Puede gestionar vehículos'), ('ver_vehiculos', 'Puede ver vehículos'), ('agregar_vehiculos', 'Puede registrar vehículos'), ('editar_vehiculos', 'Puede actualizar vehículos')],
            },
        ),
    ]
