# Generated by Django 5.2.5 on 2025-09-24 06:09

import django.core.validators
import vehiculo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900, message='El año no puede ser menor a 1900.'), vehiculo.models.validate_max_year], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cantidad_puerta',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Debe ser al menos 1.')], verbose_name='Cantidad de puertas'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='nro_chapa',
            field=models.CharField(error_messages={'unique': 'Ya existe un vehículo con esta chapa.'}, help_text='Sugerido PY: ABC123 o ABC1234; también se aceptan otros formatos alfanuméricos.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de chapa inválido (use 4–12 caracteres alfanuméricos; se permiten guion y punto).', regex='^[A-Z0-9\\-\\.]{4,12}$')], verbose_name='Nro. de chapa'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='nro_chasis',
            field=models.CharField(error_messages={'unique': 'Ya existe un vehículo con este número de chasis.'}, help_text='VIN de 17 (sin I/O/Q) o chasis antiguo 9–14.', max_length=20, unique=True, validators=[vehiculo.models.chasis_validator], verbose_name='Nro. de chasis'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='uso',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('COMERCIAL', 'Comercial'), ('OFICIAL', 'Oficial'), ('PARTICULAR_COMERCIAL', 'Particular/Comercial')], max_length=25, verbose_name='Uso'),
        ),
    ]
