# Generated by Django 5.2.5 on 2025-09-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_anio_alter_vehiculo_cantidad_puerta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
