# Generated by Django 5.2.5 on 2025-09-25 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_alter_cliente_fecha_constitucion_and_more'),
        ('vehiculo', '0003_vehiculo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='cliente.cliente', verbose_name='Dueño'),
        ),
    ]
