# Generated by Django 5.2.5 on 2025-10-14 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_alter_cliente_fecha_constitucion_and_more'),
        ('vehiculo', '0004_vehiculo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='cliente',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='poseedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_poseedor', to='cliente.cliente', verbose_name='Poseedor/Responsable'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente', verbose_name='Propietario'),
        ),
    ]
