# Generated by Django 5.2.5 on 2025-10-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_remove_vehiculo_cliente_vehiculo_poseedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[('Nafta', 'Nafta/Gasolina'), ('Diésel', 'Diésel'), ('Eléctrico', 'Eléctrico'), ('Híbrido', 'Híbrido'), ('GNC', 'GNC')], max_length=15, verbose_name='Tipo de combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='uso',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Comercial', 'Comercial'), ('Oficial', 'Oficial'), ('Particular/Comercial', 'Particular/Comercial')], max_length=25, verbose_name='Uso'),
        ),
    ]
