# Generated by Django 5.2.5 on 2025-10-28 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0006_alter_vehiculo_tipo_combustible_alter_vehiculo_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='nro_chapa',
            field=models.CharField(blank=True, error_messages={'unique': 'Ya existe un vehículo con esta chapa.'}, help_text='Sugerido PY: ABC123 o ABC1234; también se aceptan otros formatos alfanuméricos.', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de chapa inválido (use 4–12 caracteres alfanuméricos; se permiten guion y punto).', regex='^[A-Z0-9\\-\\.]{4,12}$')], verbose_name='Nro. de chapa'),
        ),
    ]
