# Generated by Django 5.2.5 on 2025-09-18 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('cedula_ruc', models.CharField(help_text='Ej.: 1234567 o 1234567-8', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Ej.: 1234567 o 1234567-8', regex='^[0-9]{5,12}(-[0-9]{1})?$')], verbose_name='Cédula/RUC')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato recomendado: +595xxxxxxx', regex='^\\+?595[0-9]{7,9}$')], verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Correo inválido')], verbose_name='Correo electrónico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario base')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ('-fecha_registro',),
                'permissions': [('gestionar_empleados', 'Puede gestionar empleados'), ('ver_empleados', 'Puede ver empleados'), ('agregar_empleados', 'Puede registrar empleados'), ('editar_empleados', 'Puede actualizar empleados'), ('desactivar_empleados', 'Puede desactivar empleados')],
            },
        ),
    ]
