# Generated by Django 5.2.5 on 2025-09-18 06:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula_ruc',
            field=models.CharField(error_messages={'unique': 'Ya existe un empleado con esta Cédula/RUC.'}, help_text='Ej.: 1234567 o 1234567-8', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Ej.: 1234567 o 1234567-8', regex='^[0-9]{5,12}(-[0-9]{1})?$')], verbose_name='Cédula/RUC'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ciudad',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo_electronico',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Correo inválido')], verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
