# Generated by Django 5.2.5 on 2025-10-25 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleado_user_alter_empleado_cedula_ruc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula_ruc',
            field=models.CharField(error_messages={'unique': 'Ya existe un empleado con esta Cédula/RUC.'}, help_text='Ej.: 1234567 o 80012345-1', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Ej.: 1234567 o 80012345-1', regex='^[0-9]{5,12}(-[0-9]{1})?$')], verbose_name='Cédula/RUC'),
        ),
    ]
