# Generated by Django 5.2.5 on 2025-11-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_alter_empleado_cedula_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='limite_horas_diarias',
            field=models.PositiveIntegerField(default=9, help_text='Horas máximas de trabajo por día para alertas de sobrecarga', verbose_name='Límite de horas diarias'),
        ),
    ]
