# Generated by Django 5.2.5 on 2026-03-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_empleado_limite_horas_diarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='comision_acumulada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisiones acumuladas de servicios completados', max_digits=15, verbose_name='Comisión acumulada'),
        ),
    ]
