# Generated by Django 5.2.5 on 2026-03-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_empleado_comision_acumulada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='limite_horas_diarias',
            field=models.PositiveIntegerField(default=8, help_text='Horas máximas de trabajo por día para alertas de sobrecarga', verbose_name='Límite de horas diarias'),
        ),
    ]
