# Generated by Django 5.2.5 on 2026-04-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0007_alter_empleado_limite_horas_diarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='comision_por_cobrar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisiones pendientes de pago (de órdenes completadas)', max_digits=15, verbose_name='Comisión por cobrar'),
        ),
    ]
