# Generated by Django 5.2.5 on 2026-04-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0008_empleado_comision_por_cobrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='comision_por_cobrar',
        ),
    ]
